### ISSUE TITLE
utf8 characters problem

### ISSUE THREAD

**Issue by meiosischen** [gizak/termui#10]
I've run the examples with utf8(Chinese) characters, but can't see right result. How to fix that? thanks.

**Comment by gizak** [comment]
If you saw missing chars, this is probably caused by wide char width calculation. There is a temporary fix: you can put a whitespace after each Chinese char and doing this may make it display all of the string. 

But another issue is, for now, termui counts every char (including CJK) as width 1, so printing wide char may not align properly.

termui highly depends on termbox-go, some same issues here: https://github.com/nsf/termbox-go/issues/18, https://github.com/nsf/termbox-go/issues/59, https://github.com/nsf/termbox-go/issues/71.

It seems that this can be handled by https://github.com/mattn/go-runewidth. I will look into it and try out soon.
