### ISSUE TITLE
Suggestion: plain-text configuration

### ISSUE THREAD

**Issue by slezica** [gizak/termui#11]
This is a surprising and awesome tool, but you need to write `Go` to use it.

Reading widgets from a configuration file, in any popular format, would make the tool easier to configure and available to a much larger range of developers.

**Comment by Matt3o12** [comment]
Good point, although you are going to need to write `Go` code eventually (unless you want to have a completely static app of course). If you only use the available widgets, you won't be able to get dynamic content.  
I currently write widgets for termui that are kind of "higher level widgets" and only  fulfill one task. The first widget is going to be a Hacker News newsfeed (that includes the top stories as well as the most recent ones). Later I will write widget that pulls my server's load (and CPU usage, memory, etc) using [new relic](http://newrelic.com). They have a pretty straightforward API and connecting your server to their service is free and super easy (it only took me a minute)*.

Right now, implementing that is kind of pointless, though. The only advantage is cleaner code but that's it. 

* just make sure you add the server to their [Server monitoring Service](http://newrelic.com/server-monitoring) and not the application service (because the usage is very limited if you don't pay).

**Comment by gizak** [comment]
Hi @slezica, it's a good idea! Reminds me of [graphite-web](https://github.com/graphite-project/graphite-web). I think this can be done by wrapping it up as a command line tool which continuously fetches data from an URI (*.json maybe). But as @Matt3o12 said, you may need some go codes if you want adding in custom logic.

Actually I've came across a similiar idea when implementing grid layout, thought a html-like tamplate would be helpful to define layout. Now this seems doable!

**Comment by RangerMauve** [comment]
Yeah, what you're describing sounds more like a project that someone should make using this as a rendering background, rather than having the library itself focus on making "html-like" directly.

**Comment by Matt3o12** [comment]
:+1:

**Comment by andyl** [comment]
+1 for plain text configuration, and for polling JSON files or URL to ingest data.  Termui is great but we can't write custom `go` code.

Another idea for data sources: add an adapter to InfluxDB.  All of our stats are stored in InfluxDB, but we don't have any way to display on the terminal.

To display InfluxDB stats on the browser we use Grafana - might be an interesting comparable for termui. 

I agree with the OP - termui is a surprising and awesome tool.  I think you are very close to having a tool that will attract a huge audience.

**Comment by fgrehm** [comment]
Another idea that would make things a bit more dynamic would be to expose a JS api through something like [otto](https://github.com/robertkrimen/otto), but I'm relatively new to termui to know if that would be doable or not :grin:

**Comment by RangerMauve** [comment]
@fgrehm If you want a JS API, why not just go with [blessed-contrib](https://github.com/yaronn/blessed-contrib) which is node-based?

**Comment by gizak** [comment]
Just open a new repo [termuid](https://github.com/gizak/termuid) in response;)

**Comment by alphapapa** [comment]
Yes, this looks really neat, but all I want to do is pipe some data to a widget and have it displayed.  It seems like a widget should be able to accept a plain number, CSV, JSON, etc.

And to be sure this isn't already possible and I wasn't missing something, I had to come find this issue... :)

**Comment by fgrehm** [comment]
I just came across https://github.com/yaronn/wopr which might be used as an inspiration

**Comment by cjbassi** [comment]
A plain text configuration is a cool idea, but it's somewhat out of the scope of termui (I think). As was mentioned, you can create a higher level widget that reads its data from a file. But the widget design itself has to be in Go.

I realize this is an older issue, but just doing some housekeeping. :smiley_cat:
