### ISSUE TITLE
Sparkline doesn't 'fill' Sparklines 

### ISSUE THREAD

**Issue by chrisgillis** [gizak/termui#15]
If I have a sparkline with 200 data points, and add it to a Sparklines that is in a Row/Col that takes up half the width of the terminal (width 6?), i can't see the newest data that should be on the sparkline. The width of the vertical bars can't adjust to scale the full range of sparkline data into the box. 

Also if I then resize the terminal to full screen, the sparkline stops about 3/4th of the way instead of filling it's box.

**Comment by gizak** [comment]
Thanks for pointing out! 

Since every widget only processes data that in displayable range, which means if you set it with a width 100, then only the first 100 elements in slice get rendered. termui makes no assumptions how to abstract data (at least for now), it merely displays data fetching visible range.

For the resizing problem, I assume you used `Align()` method on resize event, the resize event does not reflect size changing immediately, so you may experience half-way or delay resizing problems. There is a hot fix, put `Align()` method under your drawing function which gives correct rendering.:)

**Comment by chrisgillis** [comment]
It seems like that for Sparklines, if the slice has a len of 200 and the computed with is 100, it should render the last 100 elements of the slice, not the first 100; or this should be configurable.

**Comment by gizak** [comment]
Yes! Make it configurable will be nice.

**Comment by divan** [comment]
It seems that most of sparkline implementations assume left-to-right direction of the data flow, thus, the rightmost point should represent the latest actual data point.

Here is a web page called "Sparkline theory and practice" by Edward Tufte, person who coined the term "sparkline": http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR
He doesn't state the direction explicitly, but the idea of sparklines is to be *datawords*, which are easily read, just like words. In the article he uses mostly left-to-right sparklines.

So, the question is - what are the use cases for right-to-left (current) sparkline direction? Should it really to be configurable, or it's better to agree on widely accepted default direction?

**Comment by gizak** [comment]
Hey, that is a very impressive article! I think we should probably go with the most accepted convention which uses the last N datapoint, because updating data always done by appending (not prepending) datapoint.
