### ISSUE TITLE
Is it possible to integrate termui with go-ncurses?

### ISSUE THREAD

**Issue by miguelmota** [gizak/termui#173]
Hi I have a dumb question, is it possible for a termui component, such as the chart, to be rendered inside a ncurses window?

**Comment by cjbassi** [comment]
You should be able to do it for sure if you're working in Go. Otherwise you might have to port the code or do something else.

The way widgets work is that they are internally rendered to a Buffer object, so if you wanted to you could create a chart, get the Buffer object it renders to, and then work with that however you want.

A Buffer is a struct with an area and a mapping from points in the area to Cells. Cells hold the character of that given point along with color properties.

So depending on the context you'd want to use it, you could copy the code for the Buffer, the chart, and also the Block (which is used by the chart) to wherever you're running your code and then render the Buffer in whatever way you want.

**Comment by miguelmota** [comment]
@cjbassi in the end I didn't use ncurses, however what you described is exactly how I went about it. Thanks for the response
