### ISSUE TITLE
Recent changes broke Termeter, which uses this package

### ISSUE THREAD

**Issue by jake-g** [gizak/termui#220]
I have never had a problem with [termeter](https://github.com/atsaki/termeter) until recently. I suspect all the recent activity on this repo has something to do with it. Termeter relies on an older version of this project, termui.v1. Now it seems to have disappeared and termeter no longer builds. Is it possible to keep v1 so that legacy projects still work?

See: 

The error i get:

```
>  ~ go get -u github.com/atsaki/termeter/cmd/termeter

package gopkg.in/gizak/termui.v1: unrecognized import path "gopkg.in/gizak/termui.v1"
```

**Comment by cjbassi** [comment]
Can you try it now? I readded the `v1` tag and it works for me now.

**Comment by keithknott26** [comment]
I ended up writing an app just like termeter to use the new line graph features of termUI (the latest v3 code) but ended up with alot of flickering when the screen was rendered. I'll have to get a bug raised with you @cjbassi , is there a place I can send the code (which isn't ready to be made public just yet).

**Comment by cjbassi** [comment]
@keithknott26 Hmm, well I would recommend isolating the source of the flickering in your code, then creating a new issue and posting a minimal reproducible example that still causes the flickering.

Btw I was experiencing some flickering after the rewrite and it was because I had some erroneous calls to `ui.Clear()`, in case that helps.
